 - id: add-trailing-newline
   name: Add Trailing Newline
   description: Ensures that a file always ends with one blank line.
   entry: add-trailing-newline
   language: python
   types: [text]
   stages: [commit, push, manual]
