 - id: add-trailing-blank-line
   name: Add Trailing Blank line
   description: Ensures that a file always ends with one blank line.
   entry: add-trailing-blank-line
   language: python
   types: [text]
   stages: [commit, push, manual]
